### ISSUE TITLE
Configurable Options?

### ISSUE THREAD

**Issue by NolanHewitt** [Happy1speed/balanced-shield#1]
Would it be possible to add a config file that lets us change things like the percentage from different kinds of hits, and the time before the percent resets? I see there are tags, with shields given the shield tier two tag having the cooldown time cut in half, and shields with the tier one tag having no cooldown. But having maybe a couple more tiers to choose from and having the tiers also effect how many hits it takes to put them on cooldown would be nice. Something like this:

Shield Tier 4: Takes 4 hits from melee attacks, 5 arrows, 3 explosions, 1 hit from an axe or fireworks.
Shield Tier 3: Takes the same number of hits as tier 4 but also has the reduced cooldown like the current tier 2 shield tag gives
Shield Tier 2: Has the reduced cooldown just like Tier 3, but now takes 5 hits from melee, 6 arrows, 4 explosions, still 1 hit from an axe or fireworks
Shield Tier 1: Works just like the current tier 1 where it effectively has no cooldown.

**Comment by Happy1speed** [comment]
Im only able to do simple configuration files as of now and this is a lot of stuff to put in a config.
Its do-able though.

**Comment by NolanHewitt** [comment]
> Im only able to do simple configuration files as of now and this is a lot of stuff to put in a config. Its do-able though.

I'd be ok if it was just using the current tag system it uses right now if making a config file work was too much. I'd just like more tiers to choose from.

**Comment by NolanHewitt** [comment]
Thank you! Those options we have now are perfect. Though I did notice that the shield tier two tag makes shields with that tag have no cooldown at all. Is that intentional? 
Also how does the power hit tags naming convention work? I noticed things with power_two_hit take 6 hits to disable a shield, power three hit takes 4 hits, power four hit takes three hits, power six hit takes two hits to disable it, and both power twelve hit and power full hit disable in one hit. Are there any function differences between full hit and twelve hit?

**Comment by Happy1speed** [comment]
First one is a bug.

The difference between full hit and twelve is only noticeable if the defending player is using a shield tagged with "tier_four_charges" or "tier_five_charges", since those shields have more than 12 shield tolerance.

**Comment by Happy1speed** [comment]
> Thank you! Those options we have now are perfect. Though I did notice that the shield tier two tag makes shields with that tag have no cooldown at all. Is that intentional? Also how does the power hit tags naming convention work? I noticed things with power_two_hit take 6 hits to disable a shield, power three hit takes 4 hits, power four hit takes three hits, power six hit takes two hits to disable it, and both power twelve hit and power full hit disable in one hit. Are there any function differences between full hit and twelve hit?

I can confirm that shields in the "shield_tier_two" tag have a cooldown.

**Comment by NolanHewitt** [comment]
Ah I see what my issue was. The tier two shield tag has an item from a different mod in it already so if someone doesn't also have that mod installed as well as this one, then the tier two shield tag won't work by default. Though this isn't really an issue as you can simply change "replace": false, to "replace": true in the shield_tier_two.json file to overwrite the tag file included.

This doesn't cause the shield in tier two to have no cooldown though. I can't replicate that at all anymore so not sure what was up with that. It's probably not an issue.

**Comment by Happy1speed** [comment]
I might turn the guarding compat into an optional datapack. 
I would recommend using a mod that fixes tags for now.
[https://www.curseforge.com/minecraft/mc-mods/lmft](url)
