### ISSUE TITLE
Slight incompatibility with Shield Mechanics

### ISSUE THREAD

**Issue by ruax2891** [Happy1speed/balanced-shield#3]
Upon using this mod with Shield Mechanics, the shield disabling becomes very inconsistent, sometimes the disabling of the shield didn't work, other times it did
I found out that disabling Shield Mechanics' block cooldown fixed the issue, but I just wanted to let you know of the incompatiblity, maybe there's a way both features can be enabled?

**Testing Instance**:
- Minecraft 1.20.1
- Fabric Loader 0.16.9
**Mods**:
- Fabric API 0.92.2
- Balanced Shield 0.8
- Guarding 2.4.0
- Shield Mechanics 4.5
- Cupboard 2.7

**Comment by Happy1speed** [comment]
I'll take a look at it

**Comment by Happy1speed** [comment]
It looks like Shield Mechanics' Block cooldown feature applies a cooldown that overwrites Balanced shield's shield disable cooldown, which is why its not going on cooldown sometimes. Its not something I can fix unfortunately.

**Comment by ruax2891** [comment]
Thank you for the response!
Still gonna use your mod btw, the features are really nice 😁
